### ISSUE TITLE
Issues Found During Testing

### ISSUE THREAD

**Issue by LilyCathelineau** [LilyCathelineau/Arch-Linux-INI-Based-Installer-Script#2]
After testing the latest version of Arch Linux **(2018-10-01)** on a  [Virtual Machine](https://www.virtualbox.org/), I have compiled a list of bugs that need to be fixed for the program to work properly.

### To-do list 

- [ ] Arch Linux needs Data to start with a capitalized letter, I fixed this in the Virtual Machine by using [GNU/Nano](https://en.wikipedia.org/wiki/GNU_nano) to change the file names in run.sh to properly specify capitalization.  

- [ ] mkfs has an issue resulting in command "mkfs." not being found. For full context, this is because the . is followed by an INI variable name, isn't actually defined by default. Meaning "FILE_SYSTEM_TYPE" is set to nothing. This wasn't originally on purpose, and the first version of the script was meant to contain the INI variable FILE_SYSTEM_TYPE set to ext4.

- [ ] The system used currently to make partitions should be simplified. If there was a way to have it handled by the script with the user specifying file size through INI variables it would be much easier for the end user to configure.

- [ ] AMD-ucode is not found, this is probably just a capitalization issue, as amd-ucode is in the [Arch repository. ](https://www.archlinux.org/packages/core/any/amd-ucode/)

- [ ] I should add an installation tutorial, the way I managed to download and use the script was fairly simple. `wget https://github.com/LilyCathelineau/Arch-Linux-INI-Based-Installer-Script/archive/master.zip` 
`pacman -Su unzip`
`unzip master.zip` 
`cd Arch-Linux-INI-Based-Installer-Script-Master`
`sh run.sh`

Please note, that this bug list is not complete. I only got as far as the formatting point before running into issues. I did not try the actual installation with the script. I will do so after I have sorted out the issues listed above.
